########################spring配置########################
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #default-property-inclusion: non_null
  #开启热部署t
  devtools:
    restart:
      enabled: true
      #修改不重启
      exclude: static/**,templates/**
  #文件上传大小限制
  servlet:
    multipart:
      max-request-size: 3000MB
      max-file-size: 3000MB
      location: /java/lockagent/file/tmp
########################Tomcat配置########################
server:
  port: 8088
  error:
      whitelabel:
        enabled: false
  servlet:
    context-path: /lockagent
    application-display-name: lockagent
########################日志配置########################
mybatis-plus:
  mapper-locations: classpath:/com/lxkj/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lxkj.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: truek
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
########################beetl配置########################
beetlsql:
  enabled: false
########################日志配置########################

logging:
  path: /logs
  file:
    max-size: 50MB
  level:
    com.lxkj.mapper: DEBUG

########################微信配置#######################
wechat:
  mp:
    appid: wxb60e3a8b79f4e69a
    secret: 1e02ffabf4aed84e5ab6aad67d713c5e
#    callback-url: http://192.168.3.74:8088/lockagent/api/pay/callback
#    callback-url2: http://192.168.3.74:8088/lockagent/api/pay/callback2
#    wxcallback-url: http://192.168.3.74:8088/lockagent/api/pay/wxcallback
    callback-url: https://aw.wisehuitong.com/lockagent/api/pay/callback
    callback-url2: https://aw.wisehuitong.com/lockagent/api/pay/callback2
    wxcallback-url: https://aw.wisehuitong.com/lockagent/api/pay/wxcallback
    mchId: 1545294801
    mchKey: Y42MVUgJIgchBl5abYusDApYK0FsBDK5
########################图片配置 二维码海报/加盟海报/授权书#######################
picture:
  baillUrl: https://aw.wisehuitong.com/lockagentDownFile/big.jpg
  propurl: http://xiyanluo.oss-cn-beijing.aliyuncs.com/bill.jpg
  authurl: https://aw.wisehuitong.com/lockagentDownFile/auth.jpg
  zhanghurl: https://aw.wisehuitong.com/lockagentDownFile/zhang.png
